#!/bin/sh

# Add all directories in `~/.local/bin` to $PATH
export PATH="$PATH:$(find ~/.local/bin -type d | paste -sd ':' -)"

# Add brew to $PATH for macOS
export PATH=$PATH:/opt/homebrew/bin

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"


# sudo not required for some system commands
for command in mount umount sv pacman updatedb su shutdown poweroff reboot ; do
	alias $command="sudo $command"
done; unset command

#se() {
#	choice="$(find ~/.local/bin -mindepth 1 -printf '%P\n' | fzf)"
#	[ -f "$HOME/.local/bin/$choice" ] && $EDITOR "$HOME/.local/bin/$choice"
#	}

run() {
    g++ -std=c++23 -Wall -O3 -o solv "$1" && cat in | ./solv
}

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	v="nvim" \
	rsync="rsync -vrPlu" \
	mkd="mkdir -pv" \
	ffmpeg="ffmpeg -hide_banner" \
	cmp='g++ -std=c++23 -Wall -O3 -o solv' \ 

# Colorize commands when possible.
alias \
	ls="ls -h --color=auto"  \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ip="ip -color=auto"
