# -*- conf -*-
# theme: Nord
# author: Arctic Ice Studio <development@arcticicestudio.com>, Sven Greb <code@svengreb.de>
# description: „Nord“ — An arctic, north-bluish color palette
#
# this specific foot theme is based on nord-alacritty:
# https://github.com/arcticicestudio/nord-alacritty/blob/develop/src/nord.yml

font=monospace:size=14

[colors-dark]
# Core
foreground = c2c2c2        # fg-main
background = 333333        # bg-main
cursor = c2c2c2 5e5e5e     # fg-main on bg-hover-alt

# Selection
selection-foreground = c2c2c2
selection-background = 686868   # bg-hover

# Normal colors
regular0 = 333333   # black      -> bg-main
regular1 = 7c7c7c   # red        -> bg-second
regular2 = 868686   # green      -> bg-alt
regular3 = b8b8b8   # yellow     -> content-act
regular4 = 5e5e5e   # blue       -> ply-main
regular5 = 686868   # magenta    -> ply-hover
regular6 = 7c7c7c   # cyan       -> ply-act
regular7 = c2c2c2   # white      -> fg-main

# Bright colors
bright0 = 5e5e5e    # bg-hover-alt
bright1 = 868686    # bg-alt
bright2 = b8b8b8    # content-act
bright3 = c2c2c2    # fg-main
bright4 = 7c7c7c    # bg-second
bright5 = 868686    # bg-third
bright6 = 686868    # bg-hover
bright7 = ffffff    # pure white (optional highlight)

# Dim colors
dim0 = 2a2a2a
dim1 = 5e5e5e
dim2 = 686868
dim3 = 7c7c7c
dim4 = 868686
dim5 = 5e5e5e
dim6 = 686868
dim7 = b8b8b8
