general {
    col.active_border = rgba(B8B8B8FF)
    col.inactive_border = rgba(333333DD)
}
decoration {
    blur {
        enabled = true
        size = 15
        passes = 3
        vibrancy = 0.6
        vibrancy_darkness = 0.3 
    }
}

animations {
    enabled = false
}
