# ░█░█░█░█░█▀█░█▀▄░░░█░█░█▀█░█▀▄░▀█▀░█▀█░█▀▄░█░░░█▀▀░█▀▀
# ░█▀█░░█░░█▀▀░█▀▄░░░▀▄▀░█▀█░█▀▄░░█░░█▀█░█▀▄░█░░░█▀▀░▀▀█
# ░▀░▀░░▀░░▀░░░▀░▀░░░░▀░░▀░▀░▀░▀░▀▀▀░▀░▀░▀▀░░▀▀▀░▀▀▀░▀▀▀

$mainMod = SUPER

$terminal = foot
$fileManager = foot -e yazi
$menu = rofi -show drun || pkill rofi 
$browser = firefox
$screenshot = hyprshot-gui
