[mgr]
show_symlink = true
show_hidden = true

[opener]
play = [
    { run = 'vlc "$@"', desc = "VLC", orphan = true }
]
edit = [
	{ run = 'nvim "$@"', block = true, for = "unix" },
]
open = [
	{ run = 'xdg-open "$@"', desc = "Open" },
]
