[[colors.indexed_colors]]
color = "#fab387"
index = 16

[[colors.indexed_colors]]
color = "#f5e0dc"
index = 17

[colors.bright]
black = "#585b70"
blue = "#89b4fa"
cyan = "#94e2d5"
green = "#a6e3a1"
magenta = "#f5c2e7"
red = "#f38ba8"
white = "#a6adc8"
yellow = "#f9e2af"

[colors.cursor]
cursor = "#f5e0dc"
text = "#1d2021"

[colors.dim]
black = "#45475a"
blue = "#89b4fa"
cyan = "#94e2d5"
green = "#a6e3a1"
magenta = "#f5c2e7"
red = "#f38ba8"
white = "#bac2de"
yellow = "#f9e2af"

[colors.hints.end]
background = "#a6adc8"
foreground = "#1d2021"

[colors.hints.start]
background = "#f9e2af"
foreground = "#1d2021"

[colors.normal]
black = "#45475a"
blue = "#89b4fa"
cyan = "#94e2d5"
green = "#a6e3a1"
magenta = "#f5c2e7"
red = "#f38ba8"
white = "#bac2de"
yellow = "#f9e2af"

[colors.primary]
background = "#1d2021"
bright_foreground = "#cdd6f4"
dim_foreground = "#cdd6f4"
foreground = "#cdd6f4"

[colors.search.focused_match]
background = "#a6e3a1"
foreground = "#1d2021"

# [colors.search.footer_bar]
# background = "#a6adc8"
# foreground = "#1d2021"

[colors.search.matches]
background = "#a6adc8"
foreground = "#1d2021"

[colors.selection]
background = "#f5e0dc"
text = "#1d2021"

[colors.vi_mode_cursor]
cursor = "#b4befe"
text = "#1d2021"
